name: integration.yaml

on:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/**
      - cmd/**
      - internal/**
      - go.mod
      - go.sum

  pull_request:
    branches: [ "main" ]
    paths:
      - .github/workflows/**
      - cmd/**
      - internal/**
      - go.mod
      - go.sum

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: Run Integration and End to End tests
        run: go test -v -tags=integration ./...